export const categories = [
  { id: 1, title: "New", slug: "new" },
  { id: 2, title: "Office Expenses", slug: "office-expenses" },
  { id: 3, title: "Printing Stationary", slug: "printing-stationary" },
  { id: 4, title: "Entertainment", slug: "entertainment" },
  { id: 5, title: "Motor Vehicles", slug: "motor-vehicles" },
  { id: 6, title: "Travel National", slug: "travel-national" },
  { id: 7, title: "Repair Maintenance", slug: "repair-maintenance" },
  { id: 8, title: "Subscription", slug: "subscription" },
  { id: 9, title: "Salary", slug: "salary" },
  { id: 10, title: "Electricity", slug: "electricity" },
  { id: 11, title: "Internet", slug: "internet" },
  { id: 12, title: "Income Tax", slug: "income-tax" },
  { id: 13, title: "Bank Fees", slug: "bank-fees" },
  { id: 14, title: "Legal Expense", slug: "legal-expense" },
  { id: 15, title: "Insurance", slug: "insurance" },
  { id: 16, title: "Freight & Courier", slug: "freight-courier" },
  { id: 17, title: "Cleaning", slug: "cleaning" },
  { id: 18, title: "Rent", slug: "rent" },
];
